# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

      - name: Install msp430-gcc
        run: |
          wget "http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/9_2_0_0/export/msp430-gcc-full-linux-x64-installer-9.2.0.0.run"
          chmod +x ./msp430-gcc-full-linux-x64-installer-9.2.0.0.run
          sudo ./msp430-gcc-full-linux-x64-installer-9.2.0.0.run  --mode unattended --prefix /opt/msp430-gcc
          rm -f ./msp430-gcc-full-linux-x64-installer-9.2.0.0.run
          /opt/msp430-gcc/bin/msp430-elf-gcc --version

      - name: Build usb_uart_bridge
        run: make
        env:
          MSP430_TOOLCHAIN_PATH: /opt/msp430-gcc

      - name: test
        run: sh ./run_tests.sh

      - uses: actions/upload-artifact@v2
        with:
          name: usb-uart-bridge
          path: usb_uart_bridge.*
